targets:
  $default:
    builders:
      commands:
        enabled: true

builders:
  commands:
    import: "package:commanded/src/builder.dart"
    builder_factories:
      - commandBuilder
    build_extensions:
      .dart:
        - .commanded.g.part
    auto_apply: root_package
    build_to: cache
    applies_builders:
      - source_gen:combining_builder