name: advanced_cli
description: j
version: 1.0.0
repository: https://github.com/Calebh101/advanced_cli

environment:
  sdk: ^3.12.2

dependencies:
  build: ^4.0.10
  source_gen: ^4.2.4
  analyzer: ^14.1.0
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.16.0
  lints: ^6.0.0
  test: ^1.25.6
